source 'https://rubygems.org'
source 'https://rails-assets.org'

gem 'builder', '~> 3.0'
gem 'font-awesome-middleman'
gem 'middleman', '~> 3.2.1'
gem 'middleman-blog', '~> 3.5.1'
gem 'middleman-deploy'
gem 'middleman-google-analytics'
gem 'middleman-livereload'
gem 'middleman-syntax', '>= 2.0'
gem 'nokogiri'
gem 'rails-assets-gumby'
gem 'redcarpet'
gem 'slim'
