source 'https://rubygems.org'
source 'https://rails-assets.org'

gem 'builder'
gem 'font-awesome-middleman'
gem 'middleman'
gem 'middleman-blog'
gem 'middleman-deploy'
gem 'middleman-google-analytics'
gem 'middleman-livereload'
gem 'middleman-syntax'
gem 'nokogiri'
gem 'rails-assets-gumby'
gem 'redcarpet'
gem 'slim'
